### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by marcatec** [Itee/three-full#28]
I want to say thanks for your effort creating this repo. It helped us a lot.
Now that three.js has converted almost all examples to modules we made the move to directly import from three.

**Comment by Mugen87** [comment]
@ltee Yeah, your project was definitely influence factor for the main repo. It shows how important modules are for the users of the library.

However, since `three.js` has migrated almost all example code to ES6 modules, I suggest you archive this repository and the respective `npm` package.  New users might still use `three-full` although it's much better to use the modules from the main repo which are always up to date.

**Comment by Itee** [comment]
Thank to you !
See #29
